version: '3'
services:
  bot:
    image: kukks/btcpayserverslackbot
    restart: unless-stopped
    build: ./BtcPayServerSlackBot
    environment:
      - SlackApiKey
      - HelpEnabled
      - StatsEnabled
      - AboutEnabled